const menu = [
  {
    id: 1,
    title: 'wantan',
    category: 'Entrada',
    price: 2500,
    img: './images/Wantan.jpg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: 'aji relleno',
    category: 'Entrada',
    price: 6000,
    img: './images/AjiRelleno.jpeg',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 3,
    title: 'pollo frito',
    category: 'Entrada',
    price: 5500,
    img: './images/PolloFrito.jpg',
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: 'Papas fritas',
    category: 'Acompañamientos',
    price: 3200,
    img: './images/PapasFritas.jpg',
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: 'Arroz chaufan',
    category: 'Acompañamientos',
    price: 2200,
    img: './images/Chaufan.jpg',
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: 'Arroz chaufan especial',
    category: 'Acompañamientos',
    price: 8000,
    img: './images/Chaufan.jpg',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: 'Arroz blanco',
    category: 'Acompañamientos',
    price: 2200,
    img: './images/ArrozBlanco.jpg',
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: 'Chapsui de carne',
    category: 'Chapsui',
    price: 6500,
    img: './images/Chapsui.jpg',
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: 'Chapsui de pollo',
    category: 'Chapsui',
    price: 6500,
    img: './images/Chapsui.jpg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 10,
    title: 'Carne Mongoliana',
    category: 'Carne',
    price: 8700,
    img: './images/CarneMongo.jpeg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 11,
    title: 'Carne con diente de dragon',
    category: 'Carne',
    price: 7500,
    img: './images/PolloDiente.jpeg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 12,
    title: 'Pollo mongoliano',
    category: 'Pollo',
    price: 8500,
    img: './images/PolloMongoliano.jpeg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 13,
    title: 'Menu 2 Personas',
    category: 'Menu',
    price: 18700,
    img: './images/CarneMongo.jpeg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 14,
    title: 'Menu 3 Personas',
    category: 'Menu',
    price: 28500,
    img: './images/CarneMongo.jpeg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 15,
    title: 'Menu 4 Personas',
    category: 'Menu',
    price: 33500,
    img: './images/CarneMongo.jpeg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 16,
    title: 'Menu 5 Personas',
    category: 'Menu',
    price: 45500,
    img: './images/CarneMongo.jpeg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  
];
export default menu;
